name: Deploy HealthifyMe-Lite to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy static files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: healthifyme-lite
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
